# Generated by Django 3.2.6 on 2021-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='product',
            field=models.ManyToManyField(through='products.Allergy_product', to='products.Product'),
        ),
    ]
